name: "Danfoss Icon Home Assistant Addon"
description: "Danfoss Icon Home Assistant Addon"
version: "1.0.0"
slug: "danfoss"
init: false
homeassistant_api: true
map:
  - share:rw
ports:
  9090/tcp: 9090
options:
  userName: "home-assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386