name: "Danfoss Icon Addon"
description: "Danfoss Icon Master Controller Addon"
version: "0.0.22"
slug: "danfoss"
init: false
url: "https://github.com/soundvibe/ha-danfoss"
homeassistant_api: true
webui: "http://[HOST]:[PORT:9199]"
watchdog: "http://[HOST]:[PORT:9199]/health"
map:
  - share:rw
ports:
  9199/tcp: 9199
options:
  userName: "home-assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386