name: "Danfoss Icon (Custom)"
description: "Forked Danfoss Icon Master Controller Addon with unique device identifiers"
version: "0.4.6" 
slug: "danfoss_custom"
init: false
url: "https://github.com/igotyou/ha-danfoss" 
homeassistant_api: true
webui: "http://[HOST]:[PORT:9199]"
watchdog: "http://[HOST]:[PORT:9199]/health"
map:
  - share:rw
ports:
  9199/tcp: 9199
options:
  haUpdatePeriodInSeconds: 60
  sensorNameFmt: "sensor.danfoss_%d_temperature"
  port: 9199
  mqttEnabled: false
  mqttHost: core-mosquitto
  mqttPort: 1883
  mqttKeepAlive: 60
  mqttUsername: ""
  mqttPassword: ""
  logLevel: info
  m4FixEnabled: false
schema:
  haUpdatePeriodInSeconds: "int(1,86400)"
  sensorNameFmt: str
  port: port
  mqttEnabled: bool
  mqttHost: str
  mqttPort: port
  mqttKeepAlive: int
  mqttUsername: str
  mqttPassword: password
  logLevel: str
  m4FixEnabled: bool
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
