name: "Danfoss Icon"
description: "Danfoss Icon Master Controller Addon"
version: "0.3.2"
slug: "danfoss"
init: false
url: "https://github.com/soundvibe/ha-danfoss"
homeassistant_api: true
webui: "http://[HOST]:[PORT:9199]"
watchdog: "http://[HOST]:[PORT:9199]/health"
map:
  - share:rw
ports:
  9199/tcp: 9199
options:
  haUpdatePeriodInMinutes: 1
  sensorNameFmt: "sensor.danfoss_%d_temperature"
  port: 9199
  mqttEnabled: false
  mqttHost: core-mosquitto
  mqttPort: 1883
  mqttKeepAlive: 60
  mqttUsername: ""
  mqttPassword: ""
  logLevel: info
schema:
  haUpdatePeriodInMinutes: "int(1,60)"
  sensorNameFmt: str
  port: port
  mqttEnabled: bool
  mqttHost: str
  mqttPort: port
  mqttKeepAlive: int
  mqttUsername: str
  mqttPassword: password
  logLevel: str
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386