name: "Danfoss Icon Home Assistant Addon"
description: "Danfoss Icon Home Assistant Addon"
version: "1.0.0"
slug: "danfoss"
init: false
homeassistant_api: true
map:
  - share:rw
stdin: true
ports:
  9090/tcp: 9090
webui: http://localhost:9090/
watchdog: http://localhost:9090/health
host_network: true
options:
  userName: "home-assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386